server:
  port: 8080

upload:
  path: F:\self-projects\Game Software Management System Document\

spring:
  # 自定义静态资源：将保存文件的目录暴露出去，即F:\self-projects\Game Software Management System Document\
  # 使得可以通过"localhost:8080/ + 文件名"访问到 文件
  resources:
    static-locations:
      file:${upload.path},
      classpath:/META-INF/resources/,
      classpath:/resources/,
      classpath:/static/,
      classpath:/public/
  datasource:
    url: jdbc:mysql://localhost:3306/platform_db
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: -1 # 上传单个文件大小的最大限制（-1就是无限制）
      max-request-size: -1 # 上传多个文件大小的最大限制（-1就是无限制）
#打印sql语句
logging:
  level:
    com:
      justin:
        app_back:
          mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml